CREATE TABLE "GCG_6014_GUI_LABS"(
 "TERMINAL" CHAR(3),
 "JOB" CHAR(6),
 "PART" CHAR(20),
 "LOC" CHAR(2),
 "DESCRIPTION" CHAR(50),
 "DESCRIPTION2" CHAR(50),
 "LABEL_TITLE" CHAR(50),
 "LABEL_TYPE" CHAR(1),
 "LABEL_QTY" INTEGER,
 "BARCODE" CHAR(50));
